### ISSUE TITLE
Potential typo

### ISSUE THREAD

**Issue by colinfang** [sethaxen/ExponentialAction.jl#28]
In https://github.com/sethaxen/ExponentialAction.jl/blob/v0.2.8/src/parameters.jl#L54

```
Aᵖ⁺¹ = A * A
d = t_norm * sqrt(opnormest1(A))
```

Should `A` here be `Aᵖ⁺¹` instead?

Because we are calculating the 1-norm for `A^2` as in $d_p = \lVert A^p \rVert ^{1/p}$ for $p = 2$

**Comment by sethaxen** [comment]
Fixed by #29
